### ISSUE TITLE
 这个小demo怎么玩，怎么点的没反应

### ISSUE THREAD

**Issue by changning420** [KirstenDunst/GameSudoku#1]
这个小demo怎么玩，怎么点的没反应

**Comment by KirstenDunst** [comment]
先点一下相应的数字，再点你想要填这个数字在的那个小格子就好了。readme有说明的。发自我的iPhone------------------ 原始邮件 ------------------发件人: changning420  <notifications@github.com>发送时间: 2019年7月18日 18:37收件人: KirstenDunst/GameSudoku <GameSudoku@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[KirstenDunst/GameSudoku]  这个小demo怎么玩，怎么点的没反应 (#1)Closed #1.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/KirstenDunst/GameSudoku/issues/1?email_source=notifications\u0026email_token=AEY5CDUXA7SSEXBUBJ2LWYTQABBWTA5CNFSM4IEZKA62YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOSSGSWGA#event-2492279576",
"url": "https://github.com/KirstenDunst/GameSudoku/issues/1?email_source=notifications\u0026email_token=AEY5CDUXA7SSEXBUBJ2LWYTQABBWTA5CNFSM4IEZKA62YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOSSGSWGA#event-2492279576",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
